//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace DemoModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Demo
	{
		public virtual IEnumerable<Player> Player
		{
			get;
			set;
		}

		public virtual IEnumerable<Round> Rounds
		{
			get;
			set;
		}

		public virtual IEnumerable<KillEvent> KillEvent
		{
			get;
			set;
		}

		public virtual IEnumerable<GrenadeEvent> GrenadeEvent
		{
			get;
			set;
		}

	}
}

