//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace DemoModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class GrenadeEvent
	{
		public virtual Round Round
		{
			get;
			set;
		}

		public virtual Grenade Grenade
		{
			get;
			set;
		}

	}
}

