//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace DemoModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Player
	{
		public virtual int steamID
		{
			get;
			set;
		}

		public virtual int inGameID
		{
			get;
			set;
		}

		public virtual IEnumerable<KillEvent> KillEvent
		{
			get;
			set;
		}

		public virtual GrenadeEvent GrenadeThrows
		{
			get;
			set;
		}

	}
}

